#
# JBZoo Toolbox - Codestyle
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Codestyle
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Codestyle
#

name: Continuous Integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'

env:
  COLUMNS: 120
  TERM_PROGRAM: Hyper

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        xdebug: [ xdebug, none ]
        experimental: [ false ]
        include:
          - php-version: "8.0"
            experimental: true
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ matrix.xdebug }}
          tools: composer

      - name: Build the Project
        continue-on-error: ${{ matrix.experimental }}
        run: make update --no-print-directory

      - name: üß™ PHPUnit Tests
        continue-on-error: ${{ matrix.experimental }}
        run: make test --no-print-directory


  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4 ]
        experimental: [ false ]
        include:
          - php-version: "8.0"
            experimental: true
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: üëç Code Quality
        run: make codestyle --no-print-directory
        continue-on-error: ${{ matrix.experimental }}


  reports:
    name: Reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4 ]
        experimental: [ false ]
        include:
          - php-version: "8.0"
            experimental: true
          - php-version: "8.1"
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: üî• PHPBench - Performance Report
        run: make test-performance-travis --no-print-directory
        continue-on-error: ${{ matrix.experimental }}
        env:
          XDEBUG_OFF: yes

      - name: üìù Build All Reports at Once
        run: make report-all --no-print-directory
        continue-on-error: ${{ matrix.experimental }}
