#
# JBZoo Toolbox - Codestyle
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Codestyle
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Codestyle
#

name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4 ]
        xdebug: [ xdebug, none ]

    steps:
      - run: printenv
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.xdebug }}
          tools: composer:v2

      - name: Build the Project
        run: make update --no-print-directory

      - name: üìù PHPUnit Tests
        run: make test --no-print-directory


  codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Build the Project
        run: make update --no-print-directory

      - name: üìù Code Quality
        run: make codestyle --no-print-directory


  reports:
    name: Reports
    needs:
      - phpunit
      - codestyle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Build the Project
        run: make update --no-print-directory

      - name: üìù PHPBench - Performance Report
        run: make test-performance-travis --no-print-directory

      - name: Build All Reports at Once
        run: make report-all --no-print-directory
